
MAVEN_DEPS = [
    ('com.fasterxml.jackson.core', 'jackson-core',                             '2.9.0'),
    ('com.github.lookfirst',       'sardine',                                  '5.7'),
    ('com.google.code.gson',       'gson',                                     '2.8.1'),
    ('com.google.guava',           'guava',                                    '22.0'),
    ('com.jgoodies',               'forms',                                    '1.2.1'),
    ('com.spatial4j',              'spatial4j',                                '0.5'),
    ('com.vividsolutions',         'jts',                                      '1.13'),
    ('commons-codec',              'commons-codec',                            '1.10'),
    ('commons-io',                 'commons-io',                               '2.5'),
    ('commons-logging',            'commons-logging',                          '1.2'),
    ('commons-net',                'commons-net',                              '3.6'),
    ('log4j',                      'apache-log4j-extras',                      '1.2.17'),
    ('log4j',                      'log4j',                                    '1.2.17'),
    ('net.java.dev.jna',           'jna',                                      '4.4.0'),
    ('org.antlr',                  'antlr-runtime',                            '3.5.2'),
    ('org.apache.httpcomponents',  'httpclient',                               '4.5.3'),
    ('org.apache.httpcomponents',  'httpcore',                                 '4.4.6'),
    ('org.apache.lucene',          'lucene-analyzers-common',                  '6.6.0'),
    ('org.apache.lucene',          'lucene-core',                              '6.6.0'),
    ('org.apache.lucene',          'lucene-expressions',                       '6.6.0'),
    ('org.apache.lucene',          'lucene-grouping',                          '6.6.0'),
    ('org.apache.lucene',          'lucene-highlighter',                       '6.6.0'),
    ('org.apache.lucene',          'lucene-join',                              '6.6.0'),
    ('org.apache.lucene',          'lucene-memory',                            '6.6.0'),
    ('org.apache.lucene',          'lucene-misc',                              '6.6.0'),
    ('org.apache.lucene',          'lucene-queries',                           '6.6.0'),
    ('org.apache.lucene',          'lucene-queryparser',                       '6.6.0'),
    ('org.apache.lucene',          'lucene-sandbox',                           '6.6.0'),
    ('org.apache.lucene',          'lucene-spatial',                           '6.6.0'),
    ('org.apache.lucene',          'lucene-suggest',                           '6.6.0'),
    ('org.bouncycastle',           'bcmail-jdk16',                             '1.38'),
    ('org.bouncycastle',           'bcprov-jdk16',                             '1.38'),
    ('org.codehaus.groovy',        'groovy-all',                               '2.4.12'),
    ('org.devzendo',               'Quaqua',                                   '7.3.4'),
    ('org.elasticsearch',          'elasticsearch',                            '1.7.3'),
    ('org.elasticsearch',          'elasticsearch-river-couchdb',              '2.6.0'),
    ('org.ow2.asm',                'asm',                                      '5.2'),
    ('org.ow2.asm',                'asm-commons',                              '5.2'),
    ('org.slf4j',                  'slf4j-api',                                '1.7.25'),
    ('org.swinglabs',              'swing-layout',                             '1.0.3'),
    ]

OSGI_DEPS = [
    ('com.google.gson',                                          None),                      
    ('com.google.inject',                                        '3.0.0'),                      
    ('javax.annotation',                                         None),                      
    ('javax.inject',                                             None),                      
    ('javax.inject',                                             '1.0.0'),                      
    ('org.antlr.runtime',                                        None),                      
    ('org.apache.commons.lang',                                  '2.6.0'),                      
    ('org.apache.commons.lang3',                                 '3.1.0'),                      
    ('org.apache.commons.logging',                               '1.0.4'),
    ('org.eclipse.ant.core',                                     '3.1.100'),                   
    ('org.eclipse.compare',                                      '3.5.0'),
    ('org.eclipse.core.commands',                                None),                      
    ('org.eclipse.core.databinding',                             '1.4.1'),                      
    ('org.eclipse.core.databinding.beans',                       '1.2.200'),                    
    ('org.eclipse.core.databinding.observable',                  None),                      
    ('org.eclipse.core.databinding.property',                    '1.4.200'),                    
    ('org.eclipse.core.expressions',                             '3.4.0'),                     
    ('org.eclipse.core.filesystem',                              '1.2.1'),
    ('org.eclipse.core.jobs',                                    None),                      
    ('org.eclipse.core.net',                                     '1.2.200'),                    
    ('org.eclipse.core.resources',                               '3.5.0'),                     
    ('org.eclipse.core.runtime',                                 '3.11.0'),                    
    ('org.eclipse.debug.core',                                   '3.9.0'),                     
    ('org.eclipse.draw2d',                                       None),                      
    ('org.eclipse.e4.core.commands',                             '0.10.2'),                     
    ('org.eclipse.e4.core.contexts',                             '1.3.1'),                      
    ('org.eclipse.e4.core.di',                                   '1.6.0'),                      
    ('org.eclipse.e4.core.di.annotations',                       None),                      
    ('org.eclipse.e4.core.di.extensions',                        '0.11.100'),                   
    ('org.eclipse.e4.core.services',                             '2.0.100'),                    
    ('org.eclipse.e4.tools',                                     '0.12.0'),                     
    ('org.eclipse.e4.tools.services',                            '4.5.0'),                      
    ('org.eclipse.e4.ui.css.core',                               '0.10.100'),                   
    ('org.eclipse.e4.ui.css.swt',                                '0.11.0'),                     
    ('org.eclipse.e4.ui.css.swt.theme',                          '0.9.300'),                    
    ('org.eclipse.e4.ui.di',                                     '1.0.0'),                      
    ('org.eclipse.e4.ui.model.workbench',                        '1.1.0'),                      
    ('org.eclipse.e4.ui.services',                               '1.0.0'),                      
    ('org.eclipse.e4.ui.workbench',                              '1.0.0'),                      
    ('org.eclipse.e4.ui.workbench.swt',                          '0.10.1'),                     
    ('org.eclipse.emf.common',                                   '2.9.2'),                      
    ('org.eclipse.emf.databinding',                              '1.3.0'),                      
    ('org.eclipse.emf.databinding.edit',                         '1.3.0'),                      
    ('org.eclipse.emf.ecore',                                    '2.10.0'),                     
    ('org.eclipse.emf.ecore.edit',                               None),                      
    ('org.eclipse.emf.ecore.xmi',                                None),                      
    ('org.eclipse.emf.edit',                                     None),                      
    ('org.eclipse.emf.edit.ui',                                  '2.9.0'),                      
    ('org.eclipse.emf.mwe2.runtime',                             None),                      
    ('org.eclipse.emf.validation',                               None),                      
    ('org.eclipse.equinox.common',                               None),                      
    ('org.eclipse.equinox.ds',                                   '1.4.100'),                    
    ('org.eclipse.equinox.event',                                None),                      
    ('org.eclipse.equinox.p2.core',                              '2.3.0'),                      
    ('org.eclipse.equinox.p2.director.app',                      '1.0.200'),                    
    ('org.eclipse.equinox.p2.engine',                            '2.3.0'),                      
    ('org.eclipse.equinox.p2.jarprocessor',                      '1.0.1'),                     
    ('org.eclipse.equinox.p2.metadata',                          '2.2.0'),                      
    ('org.eclipse.equinox.p2.metadata.repository',               '1.2.100'),                    
    ('org.eclipse.equinox.p2.operations',                        '2.3.0'),                      
    ('org.eclipse.equinox.p2.publisher',                         '1.1.0'),                      
    ('org.eclipse.equinox.p2.publisher.eclipse',                 '1.0.0'),                      
    ('org.eclipse.equinox.p2.repository',                        '2.3.0'),                      
    ('org.eclipse.equinox.p2.repository.tools',                  '2.0.0'),                     
    ('org.eclipse.equinox.preferences',                          '3.5.200'),                    
    ('org.eclipse.equinox.registry',                             None),                      
    ('org.eclipse.equinox.security',                             '1.2.0'),                      
    ('org.eclipse.equinox.util',                                 '1.0.500'),                    
    ('org.eclipse.jdt.annotation',                               '1.0.0'),
    ('org.eclipse.jdt.core',                                     '3.8.0'),                     
    ('org.eclipse.jdt.launching',                                '3.5.0'),
    ('org.eclipse.jface',                                        '3.10.0'),                     
    ('org.eclipse.jface.databinding',                            '1.6.200'),                    
    ('org.eclipse.jface.text',                                   '3.8.101'),                    
    ('org.eclipse.osgi',                                         '3.3.0'),                     
    ('org.eclipse.osgi.services',                                '3.3.100'),                    
    ('org.eclipse.osgi.util',                                    None),                      
    ('org.eclipse.search',                                       '3.5.0'),
    ('org.eclipse.swt',                                          '3.102.1'),                    
    ('org.eclipse.team.core',                                    '3.5.0'),
    ('org.eclipse.team.ui',                                      '3.5.0'),
    ('org.eclipse.text',                                         '3.5.300'),                    
    ('org.eclipse.ui',                                           '3.105.0'),                    
    ('org.eclipse.ui.editors',                                   '3.5.0'),                      
    ('org.eclipse.ui.forms',                                     '3.4.1'),                      
    ('org.eclipse.ui.ide',                                       '3.5.0'),                      
    ('org.eclipse.ui.views',                                     '3.3.0'),                      
    ('org.eclipse.ui.workbench',                                 None),                      
    ('org.eclipse.ui.workbench.texteditor',                      '3.4.0'),                      
    ('org.eclipse.update.configurator',                          '3.1.0'),                     
    ('org.eclipse.xtend.lib',                                    None),                      
    ('org.eclipse.xtext',                                        '2.4.3'),
    ('org.eclipse.xtext.builder',                                None),                      
    ('org.eclipse.xtext.common.types',                           None),                      
    ('org.eclipse.xtext.common.types.ui',                        None),                      
    ('org.eclipse.xtext.junit4',                                 None),                      
    ('org.eclipse.xtext.ui',                                     '2.9.0'),                      
    ('org.eclipse.xtext.ui.codetemplates.ui',                    None),                      
    ('org.eclipse.xtext.ui.shared',                              None),                      
    ('org.eclipse.xtext.util',                                   '2.9.0'),                      
    ('org.eclipse.xtext.xbase.lib',                              '2.4.3'),                      
    ('org.hamcrest.core',                                        '1.3.0'),
    ('org.objectweb.asm',                                        '5.0.1'),                     
        ]
