/**
 * generated by Xtext
 */
package org.bbaw.bts.corpus.text.egy.validation;

import org.bbaw.bts.corpus.text.egy.validation.AbstractEgyDslValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class EgyDslValidator extends AbstractEgyDslValidator {
}
