/**
 * generated by Xtext
 */
package org.bbaw.bts.corpus.text.egy.ui.labeling;

import com.google.inject.Inject;
import org.bbaw.bts.corpus.text.egy.egyDsl.Chars;
import org.bbaw.bts.corpus.text.egy.egyDsl.Word;
import org.bbaw.bts.corpus.text.egy.egyDsl.WordPart;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.edit.ui.provider.AdapterFactoryLabelProvider;
import org.eclipse.xtext.ui.label.DefaultEObjectLabelProvider;

/**
 * Provides labels for a EObjects.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#labelProvider
 */
@SuppressWarnings("all")
public class EgyDslLabelProvider extends DefaultEObjectLabelProvider {
  @Inject
  public EgyDslLabelProvider(final AdapterFactoryLabelProvider delegate) {
    super(delegate);
  }
  
  public EList<WordPart> text(final Word w) {
    EList<WordPart> _wChar = w.getWChar();
    return _wChar;
  }
  
  public String text(final Chars w) {
    String _name = w.getName();
    return _name;
  }
}
